{
 "title": "Weather",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Station",
    "query": "SELECT DISTINCT station_name from weather"
   }
  ]
 },
 "panels": [
  {
   "title": "Current relative humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select TIMESTAMP(date,time) AS time, rel_hum as \"Humidity\" FROM weather\nWHERE $__timeFilter(Date) AND station_name = \"$Station\"\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select TIMESTAMP(date,time) AS time, temp as \"Temperature\" FROM weather\nWHERE $__timeFilter(Date) AND station_name = \"$Station\"\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Current wind direction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP(date,time) as time,\n  winddir as \"Direction\"\nFROM weather\nWHERE $__timeFilter(time) AND station_name = \"$Station\"\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP(date,time) as time,\n  Rainfall\nFROM weather\nWHERE $__timeFilter(time) and station_name = \"$Station\"\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Cumulative rainfall and evapotranspiration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    date as time,\n    rainfall\n  from aggregated_weather where $__timeFilter(date) and station_name = \"$Station\"\n  group by time\n) select time, sum(rainfall) over (order by time) as Rainfall from data;\n"
    },
    {
     "rawSql": "with data as (\n  select\n    date as time,\n    ETo\n  from aggregated_weather where $__timeFilter(date) and station_name = \"$Station\"\n  group by time\n) select time, sum(ETo) over (order by time) as ETo from data;"
    }
   ]
  },
  {
   "title": "Daily rainfall vs Evapotranspiration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP(Date,'YYYY-MM-DD') as time,  (Rainfall - ETo) as Difference FROM aggregated_weather\nWHERE $__timeFilter(Date) AND station_name = \"$Station\"\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "select TIMESTAMP(date,time) as time, temp as \"Temperature\" from weather\nWHERE $__timeFilter(Date) AND station_name = \"$Station\"\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "rawSql": "select TIMESTAMP(date,time) as time, windspeed as \"Windspeed\" from weather\nWHERE $__timeFilter(Date) AND station_name = \"$Station\"\nORDER BY time ASC\n"
    }
   ]
  }
 ]
}